project:
  type: website
  output-dir: ../docs

website:
  title: "Geomarketing UFF"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: tutorials/introducao_geomarketing.qmd
        text: Introdução ao Geomarketing
      - href: tutorials/preparacao_dados.qmd
        text: Preparação de Dados
      - href: tutorials/analise_localizacao.qmd
        text: Análise de Localização

format:
  html:
    theme: journal
    toc: true
    number-sections: true
    embed-resources: true

bibliography: tutorials/references.bib
csl: tutorials/planeta-zotero-abnt.csl
